### ISSUE TITLE
List source in home assistant uses "running apps" list doesn't contain all apps

### ISSUE THREAD

**Issue by imduffy15** [JeffLIrion/python-androidtv#217]
The list sources option in home assistant uses the list returned by "running apps" however, this doesn't include all apps, only running ones.

For me, on a nvidia shield this means that many apps to not appear.

It would make more sense to use "installed apps" as provided by:

```
pm list packages | awk -F : '{print $2}'
```

For my own personal use I've forked this library and made this change https://github.com/imduffy15/python-androidtv/commit/c4e1558943a832c74ba2f3fd8ca5497fd793fe13 it would be great to see it upstream or understand the reasoning for listing running apps only.

**Comment by JeffLIrion** [comment]
I used the running apps because

* That's what the `firetv` package uses, and this package originated from there. 
* It doesn't make sense to fetch the list of all apps on every update, since that list will only change when you install or delete an app. 

If you want to display the list of all apps in Home Assistant, the process should be:

1. Add a method here for obtaining the list of all apps. 
2. Add an option in Home Assistant to display all installed apps, instead of the running apps. If that option is true, then fetch the list of all apps when setting up the media player in HA. Also, register a service to update the list of all apps that a user can call after installing or deleting apps. 

Regarding the second point, I think it's no longer permitted to add YAML configuration entries, so that would require adding config flow to the integration.

**Comment by imduffy15** [comment]
Resolved on the androidtv side with https://github.com/JeffLIrion/python-androidtv/commit/33bb75b108f377dd6e0f4148f707abc9dab28a7d

Will follow up shortly on the home assistant side of things.
