### ISSUE TITLE
Use USB for adb connection

### ISSUE THREAD

**Issue by Tiebe** [JeffLIrion/python-androidtv#242]
Would this be possible? I have an Android TV that only supports adb over usb, and I am currently using an USB-A male to male cable to use adb and it works fine. Would it be possible to use this with home assistant over usb?

**Comment by JeffLIrion** [comment]
It should be possible. 

There are two ways to communicate via ADB with the Android TV device: the Python implementation ([`adb-shell`](https://github.com/JeffLIrion/adb_shell)) and using an ADB server. 

`adb-shell` has experimental support for connecting via USB, meaning it's not thoroughly tested and robust. 

If you use an ADB server, then it shouldn't matter whether that server is connected to the device via USB or TCP. Of course, you need to setup this server. 

Also, if you use the Python implementation, then the Home Assistant configuration (as well as this package) would need to be modified so that you can connect via USB. And since Home Assistant doesn't allow additional YAML configuration options, this would first require adding config flow. And all of this is quite a bit of work. 

But if you setup an ADB server that connects to your device via USB, then the current integration _**probably**_ works.

**Comment by Tiebe** [comment]
I actually did try to modify both this package and the home assistant integration, but I found that there wasn't an UsbAsync class in adb-shell, so I gave up on that.

How would I go about setting up an adb server?

**Comment by JeffLIrion** [comment]
You could try the non-ADB server route. You would need to create an `ADBPythonUSBSync` class, similar to this class:

https://github.com/JeffLIrion/python-androidtv/blob/a2a0f33e4091768cf3e7ed30cedbb6f85f308d53/androidtv/adb_manager/adb_manager_sync.py#L61

Then create an async wrapper around that class, like this:

https://github.com/JeffLIrion/python-androidtv/blob/a2a0f33e4091768cf3e7ed30cedbb6f85f308d53/androidtv/adb_manager/adb_manager_async.py#L24-L57

And then enable the setup to use that class.

**Comment by JeffLIrion** [comment]
It _might_ work using the `usb` branch. If your HA installation allows you to install Python packages, you should be able to test this via:

```
pip install adb-shell[usb]
pip install https://github.com/JeffLIrion/python-androidtv/archive/usb.zip
```

And then in your HA config, use an empty string for the host (`host: ""`).

**Comment by JeffLIrion** [comment]
This was implemented in https://github.com/JeffLIrion/python-androidtv/pull/243. But note that USB support in `adb-shell` is experimental, and it also requires an extra package to be installed. Furthermore, this package doesn't always play nicely with various operating systems. 

But from the perspective of this package, this task is done.
