### ISSUE TITLE
Platform not retrying to setup

### ISSUE THREAD

**Issue by larena1** [JeffLIrion/python-androidtv#246]
When the TV device is turned off and can't be reached, the platform will return PlatformNotReady.
Home Assistant would then normally try to setup the platform again later, but you forbid it that.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/androidtv/media_player.py#L196

Is there any reason for that? The platform will then never become available even when the TV device was turned on after

**Comment by JeffLIrion** [comment]
When setting up the platform:

1. If successful, the "IP:PORT" string gets added to the `hass.data["androidtv"]` dictionary: https://github.com/home-assistant/core/blob/c242e56b8c9eb2b4de51aac24406e638cfa843de/homeassistant/components/androidtv/media_player.py#L259
2. If setup fails, it raises `PlatformNotReady` and tries again. Note that the "IP:PORT" string does not get added to the `hass.data["androidtv"]` dictionary in this scenario. 
3. If that device, uniquely specified by its "IP:PORT" string, has already been setup, then it just exits setup at the place you linked because the device has already been setup. (This scenario probably never even happens -- why would HA try to setup the same device twice? Maybe if there is a duplicate entry in the config?)

If the device has been setup and the ADB connection gets broken -- i.e., the device becomes unavailable -- HA will try to reconnect at each update. 

I don't see a bug here. Am I missing something?

**Comment by larena1** [comment]
You are right. I quickly looked over the code then and misread the condition.

```
2021-06-12 18:01:13 ERROR (MainThread) [homeassistant.components.media_player] Setup of platform androidtv is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2021-06-12 18:02:30 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to XXX:5555.  TimeoutError: Connect call failed ('XXX', 5555)
2021-06-12 18:02:30 WARNING (MainThread) [homeassistant.components.androidtv.media_player] Could not connect to XXX at XXX:5555 using Python ADB implementation with adbkey='/home/hass/.homeassistant/.storage/androidtv_adbkey'
2021-06-12 18:02:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/androidtv/media_player.py", line 230, in async_setup_platform
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady: None
```

I did temporarily block access to the TV device via iptables to simulate the device being off. The entity will always stay unavailable after that until restarting HA.

It's also taking substantially longer for the connection to time out than the 10 seconds you pass as timeout somehow.

**Comment by JeffLIrion** [comment]
> I did temporarily block access to the TV device via iptables to simulate the device being off. The entity will always stay unavailable after that until restarting HA.

It should keep retrying every 10, 20, 30, 60, 180, 180, ... seconds until it succeeds, at which time the entity will be available. 

> It's also taking substantially longer for the connection to time out than the 10 seconds you pass as timeout somehow.

That's a bug. The `connect()` function in `adb_shell` takes 3 timeout parameters, but only one is provided ([source](https://github.com/JeffLIrion/adb_shell/blob/195d180930a7da4e804246a2820ca34810116846/adb_shell/adb_device_async.py#L208-L214)). As it is, there's no timeout on opening a socket connection to the device. But it looks like HA times out the attempt after a minute, so I think it should still setup the entity if the device goes back online (or in your case, if you unblock access to the device).

**Comment by larena1** [comment]
It will not retry to setup. It apparently does also not catch that exception and that might cause it to never retry. Maybe the time is just too long and thus the exception handler will not catch the exception?
