### ISSUE TITLE
Select source does not work after boot

### ISSUE THREAD

**Issue by TheZoker** [JeffLIrion/python-androidtv#30]
The `media_player.select_source` on my Fire TV does only work after I opened any application. So right after starting the device, this does not have any affect. When I start netflix for example, I can then also start spotify and all other applications. 
I'm not sure of this is a issue of the library or is a bug on the Fire TV itself.
Same applies when the device is in `Idle` mode (screensaver on the Fire TV).

Maybe someone can test this and we can narrow it down.

**Comment by JeffLIrion** [comment]
Home Assistant might not allow the `media_player.select_source` service to be executed when the state is idle. And I'm not sure what you mean about it only working after you've opened an application. I haven't experienced that myself. 

Also, when using the Home Assistant component, it's often easier to debug things when using the `androidtv.adb_command` service rather than HA's services.

**Comment by TheZoker** [comment]
I mean that right after the start it does not work. When I open an app (select it with the remote) then it works. 

What would be the correct command to start an app with `androidtv.adb_command`?

**Comment by JeffLIrion** [comment]
https://github.com/JeffLIrion/python-androidtv/blob/8e24c98ab1d708933075d3617ab889af3e9a8f98/androidtv/firetv.py#L237

**Comment by JeffLIrion** [comment]
Any update? The command that will be sent is `monkey -p android.intent.category.LAUNCHER -c com.netflix.ninja 1; echo $?`

**Comment by TheZoker** [comment]
I want to test this on multiple fire TV devices first and let you know about my findings.
Thanks for the full command
